name: flutter_application_02
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pedometer: ^4.0.2
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.69.0
  google_fonts: ^6.1.0
  phosphor_flutter: ^2.0.1
  fluttertoast: ^8.2.4

  table_calendar: ^3.0.9
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
